# Generated by Django 5.1.6 on 2025-03-02 02:14

from django.db import migrations
from django.contrib.auth import get_user_model
from django.utils import timezone


def create_superuser(apps, scmkhema_editor):
    User = get_user_model()

    if User.objects.exists():
        return

    superuser = User.objects.create_superuser(
        username="example_username",
        email="example@example.com",
        password="example_password",
        last_login=timezone.now(),
    )
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_superuser)]
