# Generated by Django 5.1.6 on 2025-03-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_created_at_alter_article_twitter_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
