name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Launch compose system
      run: docker compose up -d
    - name: Run Playwright tests
      run: docker compose exec web poetry run pytest